### ISSUE TITLE
How to run `bls12_isogeny_computer.sage` script?

### ISSUE THREAD

**Issue by hujw77** [arkworks-rs/curves#165]
## Summary of Bug

I run the bls12_isogeny_computer.sage script by the command `sage bls12_isogeny_computer.sage`.

Error logs below:

```sh
Traceback (most recent call last):
  File "sage/structure/category_object.pyx", line 839, in sage.structure.category_object.CategoryObject.getattr_from_category (build/cythonized/sage/structure/category_object.c:7204)
KeyError: 'point_homset'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/schemes/projective/projective_subscheme.py", line 122, in point
    return self._point(self.point_homset(), v, check=check)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/schemes/elliptic_curves/ell_point.py", line 259, in __init__
    point_homset = curve.point_homset()
                   ^^^^^^^^^^^^^^^^^^
  File "sage/structure/category_object.pyx", line 833, in sage.structure.category_object.CategoryObject.__getattr__ (build/cythonized/sage/structure/category_object.c:7123)
  File "sage/structure/category_object.pyx", line 848, in sage.structure.category_object.CategoryObject.getattr_from_category (build/cythonized/sage/structure/category_object.c:7289)
  File "sage/cpython/getattr.pyx", line 356, in sage.cpython.getattr.getattr_from_other_class (build/cythonized/sage/cpython/getattr.c:2706)
AttributeError: 'sage.rings.finite_rings.element_pari_ffelt.FiniteFieldElement_pari_ffelt' object has no attribute '__custom_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/structure/sequence.py", line 450, in __init__
    x[i] = universe(x[i])
           ^^^^^^^^^^^^^^
  File "sage/structure/parent.pyx", line 896, in sage.structure.parent.Parent.__call__ (build/cythonized/sage/structure/parent.c:9516)
  File "sage/structure/coerce_maps.pyx", line 161, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_ (build/cythonized/sage/structure/coerce_maps.c:4840)
  File "sage/structure/coerce_maps.pyx", line 156, in sage.structure.coerce_maps.DefaultConvertMap_unique._call_ (build/cythonized/sage/structure/coerce_maps.c:4732)
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/categories/sets_cat.py", line 1010, in _element_constructor_from_element_class
    return self.element_class(self, *args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sage/rings/finite_rings/element_pari_ffelt.pyx", line 341, in sage.rings.finite_rings.element_pari_ffelt.FiniteFieldElement_pari_ffelt.__init__ (build/cythonized/sage/rings/finite_rings/element_pari_ffelt.c:3736)
  File "sage/rings/finite_rings/element_pari_ffelt.pyx", line 397, in sage.rings.finite_rings.element_pari_ffelt.FiniteFieldElement_pari_ffelt.construct_from (build/cythonized/sage/rings/finite_rings/element_pari_ffelt.c:4055)
TypeError: no coercion defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sage/categories/map.pyx", line 780, in sage.categories.map.Map.__call__ (build/cythonized/sage/categories/map.c:7017)
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/schemes/elliptic_curves/ell_generic.py", line 582, in __call__
    return plane_curve.ProjectivePlaneCurve.__call__(self, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/schemes/generic/scheme.py", line 266, in __call__
    return self.point(args)
           ^^^^^^^^^^^^^^^^
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/schemes/projective/projective_subscheme.py", line 124, in point
    return self._point(self, v, check=check)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/schemes/elliptic_curves/ell_point.py", line 272, in __init__
    v = Sequence(v, R)
        ^^^^^^^^^^^^^^
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/structure/sequence.py", line 266, in Sequence
    return Sequence_generic(x, universe, check, immutable, cr, cr_str, use_sage_types)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/tmp/sage-10.0-current/local/var/lib/sage/venv-python3.11.1/lib/python3.11/site-packages/sage/structure/sequence.py", line 452, in __init__
    raise TypeError("unable to convert {} to an element of {}"
TypeError: unable to convert 92656596759244498130828963753907968110007873365071290181106087243768377627983634113826727000154150730961337906067*X2 + 5686222589310647169557844363658943733572305388244218174554731922275701639384320061976431434204712229824732289989 to an element of Finite Field in X6 of size 258664426012969094010652733694893533536393512754914660539884262666720468348340822774968888139573360124440321458177^6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/echo/workspace/zk/arkworks/curves/bls12_377/scripts/bls12_isogeny_computer.sage.py", line 312, in <module>
    g1_iso, g2_iso = bls12_377_isos()
                     ^^^^^^^^^^^^^^^^
  File "/Users/echo/workspace/zk/arkworks/curves/bls12_377/scripts/bls12_isogeny_computer.sage.py", line 116, in bls12_377_isos
    assert iso_G2_F6(Ell2_prime.random_point()).curve() == Ell2_6
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "sage/categories/map.pyx", line 782, in sage.categories.map.Map.__call__ (build/cythonized/sage/categories/map.c:7097)
TypeError: (92656596759244498130828963753907968110007873365071290181106087243768377627983634113826727000154150730961337906067*X2 + 5686222589310647169557844363658943733572305388244218174554731922275701639384320061976431434204712229824732289989 : 248046677250249017986114874024006682457694007097948347830762628632585928619585110116869864652763039160563073414223*X2 + 250439256373287637607099457426277997407272350365845484661341840733186665031693545909968721333419263425439379885919 : 1) fails to convert into the map's domain Elliptic Curve defined by y^2 = x^3 + 258664426012969093767803788900155375310718423333002228745348378504588969913928960986831280324668974484999943225339*X6^4*x + 51732885202593818802130546738978706707278702550982932107976852533344093669668164554993777627914672024888064291631*X6^3 over Finite Field in X6 of size 258664426012969094010652733694893533536393512754914660539884262666720468348340822774968888139573360124440321458177^6, but a `pushforward` method is not properly implemented
``` 

## Version
`master`

## Steps to Reproduce

`sage bls12_isogeny_computer.sage`

My sage version is `SageMath version 10.0, Release Date: 2023-05-20`

**Comment by mmagician** [comment]
@drskalman Maybe you can help?

**Comment by burdges** [comment]
What curve?  If it's BLS12-377 then you should use Elligator 2, not the isogeny for hash-to-curve.
